{
  "name": "@yo1dog/multi-error",
  "version": "2.0.0",
  "description": "Multiple error handling.",
  "type": "commonjs",
  "main": "dist/multiError.js",
  "types": "dist/multiError.d.ts",
  "engines": {
    "node": ">=12.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "npx tsc -p . --noEmit && npx eslint . --ext .js,.jsx,.ts,.tsx",
    "build": "tsc",
    "clean": "rm -rf dist",
    "prepack": "npm run clean && npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/yo1dog/node-multi-error.git"
  },
  "author": "Mike \"yo1dog\" Moore",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/yo1dog/node-multi-error/issues"
  },
  "homepage": "https://github.com/yo1dog/node-multi-error#readme",
  "devDependencies": {
    "@types/node": "^14.14.20",
    "@typescript-eslint/eslint-plugin": "^4.13.0",
    "@typescript-eslint/parser": "^4.13.0",
    "eslint": "^7.17.0",
    "typescript": "^4.1.3"
  }
}
